### ISSUE TITLE
Property 'update' does not exist on type 'NextAuthResult

### ISSUE THREAD

**Issue by fsdevriver** [RicardoGEsteves/AuthV5-Toolkit#175]
Regarding the 'update' callback in ServerSide auth, it keeps returning an error:
Property 'update' does not exist on type 'NextAuthResult

**Comment by RicardoGEsteves** [comment]
> Regarding the 'update' callback in ServerSide auth, it keeps returning an error: Property 'update' does not exist on type 'NextAuthResult

You have to update config files, based on the latest changes. That's probably a typescript error. Check auth.config.ts and auth.ts.
