### ISSUE TITLE
Refactor and update project to latest versions

### ISSUE THREAD

**Issue by RicardoGEsteves** [RicardoGEsteves/AuthV5-Toolkit#187]
- Update configs and setup for latest versions
- Refactor and update project to latest versions

**Comment by fsdevriver** [comment]
Is there any plan to update it soon?  I want to use it on my new project.
Thanks

**Comment by RicardoGEsteves** [comment]
> Is there any plan to update it soon? I want to use it on my new project. Thanks

Hi fsdevriver, yes, I want to update the repository soon. But I haven't had time lately. When I have time I will do it for sure. It's a priority on my TODO list.
